import 'package:dio/dio.dart';
import 'package:nimbus/core/utils/app_constants.dart';
import 'package:nimbus/data/models/location_model.dart';

class GeocodingApiService {
  final Dio _dio;
  final String _apiKey;

  GeocodingApiService(this._dio, {this. _apiKey = MapTilerApiConstants.apiKey});

  Future<List<LocationModel>> getLocationsFromZipcode(String zipcode) async {
    try {
      final response = await _dio.get(
        'https://api.maptiler.com/geocoding/$zipcode.json',
        queryParameters: {
          'key': _apiKey,
        },
      );

      if (response.statusCode == 200) {
        final features = response.data['features'] as List;
        if (features.isNotEmpty) {
          // Assuming the first result is the most relevant
          final feature = features[0];
          final center = feature['center'] as List<dynamic>;
          final placeName = feature['place_name'] as String;
          final context = feature['context'] as List<dynamic>;

          String cityName = '';
          String stateName = '';

          for (var item in context) {
            if (item['id'].startsWith('place')) {
              cityName = item['text'];
            } else if (item['id'].startsWith('region')) {
              stateName = item['text'];
            }
          }

          return [
            LocationModel(
              id: 0, // Will be generated by local DB
              zipcode: zipcode,
              cityName: cityName,
              stateName: stateName,
              latitude: center[1],
              longitude: center[0],
            ),
          ];
        } else {
          return [];
        }
      } else {
        throw Exception('Failed to load geocoding data: ${response.statusCode}');
      }
    } on DioException catch (e) {
      throw Exception('Failed to connect to geocoding service: ${e.message}');
    }
  }
}
